// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmRTDf2Q2WpEod1b2yOmRDalwYv-kk1J4',
    appId: '1:261090990314:web:a02e7a541e139ecd195f93',
    messagingSenderId: '261090990314',
    projectId: 'todo-usingfirebase',
    authDomain: 'todo-usingfirebase.firebaseapp.com',
    storageBucket: 'todo-usingfirebase.appspot.com',
    measurementId: 'G-F6JT06FFQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5-67V0LGpyTQYAgHFQnAoDHBNGu7eH4',
    appId: '1:261090990314:android:0a776ba7384ecb2c195f93',
    messagingSenderId: '261090990314',
    projectId: 'todo-usingfirebase',
    storageBucket: 'todo-usingfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AIXk04idYqy1UVyg049z1OmqwkTQ3Lk',
    appId: '1:261090990314:ios:ac962c3a68549c14195f93',
    messagingSenderId: '261090990314',
    projectId: 'todo-usingfirebase',
    storageBucket: 'todo-usingfirebase.appspot.com',
    iosClientId: '261090990314-pn4t2gsretp9uuuujnbb1nqe0konuki0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6AIXk04idYqy1UVyg049z1OmqwkTQ3Lk',
    appId: '1:261090990314:ios:ac962c3a68549c14195f93',
    messagingSenderId: '261090990314',
    projectId: 'todo-usingfirebase',
    storageBucket: 'todo-usingfirebase.appspot.com',
    iosClientId: '261090990314-pn4t2gsretp9uuuujnbb1nqe0konuki0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistFirebase',
  );
}
